Repository voiceflow/alexa-runtime, pull requests merged in 2020-11, with the labels that each got.

#99 feat: dynamically retrieve server data api token
  .env.test
  README.md
  backend/serviceManager.ts
  config.ts
  lib/clients/index.ts
  package.json
  server.ts
  tests/smokeTest/smokeTestRunner.ts
  types.ts
  yarn.lock
Labels: in progress

#101 fix: apl video ended events
  lib/services/alexa/request/aplUserEvent.ts
  lib/services/voiceflow/handlers/display/constants.ts
  lib/services/voiceflow/handlers/display/index.ts
  lib/services/voiceflow/handlers/display/utils.ts
Labels: ready for review

#100 feat: persist chips on reprompt (CORE-4355)
  lib/services/voiceflow/handlers/noMatch.ts
  package.json
  tests/lib/services/voiceflow/handlers/noMatch.unit.ts
  yarn.lock
Labels: ready for review

#103 feat: mongo session storage
  backend/serviceManager.ts
  config.ts
  lib/clients/index.ts
  lib/clients/mongodb.ts
  lib/clients/utils.ts
  lib/constants/index.ts
  lib/services/alexa/index.ts
  lib/services/alexa/mongo.ts
  package.json
  tests/lib/clients/index.unit.ts
  tests/lib/clients/mongodb.unit.ts
  tests/lib/services/alexa/index.unit.ts
  tests/lib/services/alexa/mongo.unit.ts
  types.ts
  yarn.lock
Labels: ready to merge

#104 fix: null choices not handled
  lib/services/voiceflow/handlers/interaction.ts
Labels: ready for review
