Repository voiceflow/alexa-runtime, pull requests merged in 2021-09, with the labels that each got.

#196 feat: replace moment by dayjs (VF-1431)
  lib/services/runtime/handlers/reminder.ts
  package.json
  pluginSetup.ts
  start.ts
  tests/setup.ts
  yarn.lock
Labels: ready to merge, autorebase:opt-in

#195 fix: unhash skill id for analytics (VF-1685)
  lib/clients/analytics.ts
  lib/clients/index.ts
  package.json
  tests/lib/clients/analytics.unit.ts
  yarn.lock
Labels: ready for review

#197 fix: use PlatformType (VF-1544)
  lib/clients/index.ts
  lib/services/alexa/request/lifecycle/initialize.ts
  package.json
  tests/lib/services/adapter/fixtures.ts
  tests/lib/services/alexa/request/lifecycle/initialize.unit.ts
  yarn.lock
Labels: ready for review

#199 feat: add amazon pay to user info step (VF-1845)
  lib/services/runtime/handlers/userInfo/utils.ts
  tests/lib/services/voiceflow/handlers/userInfo/utils.unit.ts
Labels: ready for review

#201 fix: add tests (VF-1872)
  lib/services/alexa/request/event/index.ts
  tests/lib/clients/analytics.unit.ts
  tests/lib/services/alexa/request/event/index.unit.ts
  tests/lib/services/alexa/request/event/runtime.unit.ts
  tests/lib/services/voiceflow/handlers/displayV2/rename.unit.ts
Labels: ready to merge

#200 fix: update typescript (VF-1841)
  .eslintignore
  .eslintrc.js
  backend/index.ts
  backend/serviceManager.ts
  config.ts
  lib/clients/analytics.ts
  lib/constants/index.ts
  lib/index.ts
  lib/services/adapter/index.ts
  lib/services/adapter/types.ts
  lib/services/adapter/utils.ts
  lib/services/alexa/mongo.ts
  lib/services/alexa/request/audioPlayerEvent.ts
  lib/services/alexa/request/event/runtime.ts
  lib/services/alexa/request/index.ts
  lib/services/alexa/request/lifecycle/index.ts
  lib/services/alexa/request/lifecycle/response.ts
  lib/services/alexa/types.ts
  lib/services/runtime/handlers/cancelPayment.ts
  lib/services/runtime/handlers/capture.ts
  lib/services/runtime/handlers/card.ts
  lib/services/runtime/handlers/display/index.ts
  lib/services/runtime/handlers/display/responseBuilder.ts
  lib/services/runtime/handlers/display/types.ts
  lib/services/runtime/handlers/display/utils.ts
  lib/services/runtime/handlers/events.ts
  lib/services/runtime/handlers/interaction.ts
  lib/services/runtime/handlers/payment.ts
  lib/services/runtime/handlers/reminder.ts
  lib/services/runtime/handlers/state/stream.ts
  lib/services/runtime/handlers/stream.ts
  lib/services/runtime/handlers/userInfo/utils.ts
  lib/services/runtime/types.ts
  lib/services/runtime/utils.ts
  lib/services/types.ts
  lib/services/utils.ts
  lib/utils.ts
  package.json
  server.ts
  tests/smoke/initSmokeTest.ts
  types.ts
  typings/voiceflow__backend-utils.d.ts
  yarn.lock
Labels: ready to merge
